# Generated by Django 3.2 on 2023-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramen',
            name='ingredient_choice',
            field=models.IntegerField(choices=[(1, 'Egg'), (2, 'Chicken'), (3, 'Pork')], default=1),
        ),
        migrations.AddField(
            model_name='ramen',
            name='noodle_choice',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
        ),
        migrations.AddField(
            model_name='ramen',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ramen',
            name='side_dish',
            field=models.IntegerField(choices=[(1, 'Pork dumpling'), (2, 'Beef dumpling')], default=1),
        ),
        migrations.AddField(
            model_name='ramen',
            name='soup_choice',
            field=models.IntegerField(choices=[(1, 'Beef soup'), (2, 'Pork soup')], default=1),
        ),
    ]
