# Generated by Django 3.2 on 2023-08-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_sushi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushi',
            name='INARI_SUSHI',
            field=models.IntegerField(choices=[(1, 'Inari Sushi'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='MAKI_SUSHI',
            field=models.IntegerField(choices=[(1, '6 with 3 kinds of fish salmon, tuna, amberjack'), (2, '6 with cucumber, carrot and egg'), (3, '6 with sesame topping, cucumber, egg and crab stick inside'), (4, 'None')], default=3),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='NIGIRI_SUSHI',
            field=models.IntegerField(choices=[(1, 'raw Salmon'), (2, 'raw Tuna'), (3, 'shrimp'), (4, 'sea urchin (Uni)'), (5, 'Ikura'), (6, 'Amberjack'), (7, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='TEMAKI_SUSHI',
            field=models.IntegerField(choices=[(1, ' with Crab Stick, carrot and cucumber'), (2, 'With shrimp and cucumber'), (3, 'With Ikura, egg, and salad vegetables'), (4, 'With salmon'), (5, 'None')], default=4),
        ),
    ]
