# Generated by Django 3.2 on 2023-08-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
