# Generated by Django 3.2 on 2023-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_drinks_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='BEER',
            field=models.IntegerField(choices=[(1, 'bottle'), (2, 'None')], default=1),
        ),
        migrations.AddField(
            model_name='drink',
            name='CHOYA',
            field=models.IntegerField(choices=[(1, 'bottle'), (2, 'None')], default=1),
        ),
        migrations.AddField(
            model_name='drink',
            name='GREEN_TEA',
            field=models.IntegerField(choices=[(1, 'cup'), (2, 'None')], default=1),
        ),
        migrations.AddField(
            model_name='drink',
            name='SAKE',
            field=models.IntegerField(choices=[(1, 'bottle'), (2, 'None')], default=1),
        ),
        migrations.AddField(
            model_name='drink',
            name='WATER',
            field=models.IntegerField(choices=[(1, 'cup'), (2, 'None')], default=1),
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
