# Generated by Django 3.2 on 2023-08-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20230802_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.drink')),
                ('ramen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.ramen')),
                ('sushi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.sushi')),
            ],
        ),
    ]
