# Generated by Django 3.2 on 2023-08-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramen',
            name='noodle_choice',
        ),
    ]
