# Generated by Django 3.2 on 2023-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20230805_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='BEER',
            field=models.IntegerField(choices=[(1, '1 bottle'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='CHOYA',
            field=models.IntegerField(choices=[(1, '1 bottle'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='GREEN_TEA',
            field=models.IntegerField(choices=[(1, '1 cup'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='SAKE',
            field=models.IntegerField(choices=[(1, '1 bottle'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='WATER',
            field=models.IntegerField(choices=[(1, '1 cup'), (2, 'None')], default=1),
        ),
    ]
