# Generated by Django 3.2 on 2023-08-19 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_drink_beer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
    ]
