# Generated by Django 3.2 on 2023-08-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_booktime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktime',
            old_name='book_time',
            new_name='BOOK_TIME',
        ),
    ]
