# Generated by Django 3.2 on 2023-08-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_rename_book_time_booktime_book_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTime',
        ),
    ]
