# Generated by Django 3.2 on 2023-09-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_delete_booktime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
                ('People', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
