# Generated by Django 3.2 on 2023-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm',
            name='People',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
