# Generated by Django 3.2 on 2023-09-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_confirm_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='confirm',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='confirm',
            old_name='People',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='confirm',
            old_name='Time',
            new_name='time',
        ),
    ]
