# Generated by Django 3.2 on 2023-09-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20230906_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='date',
            new_name='arriving_date',
        ),
        migrations.RenameField(
            model_name='confirm',
            old_name='time',
            new_name='dinning_time',
        ),
        migrations.RenameField(
            model_name='confirm',
            old_name='people',
            new_name='number_of_people',
        ),
        migrations.RenameField(
            model_name='confirm',
            old_name='name',
            new_name='your_name',
        ),
    ]
