# Generated by Django 3.2 on 2023-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_sushi_nigiri_sushi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='toppings_choice',
            field=models.IntegerField(choices=[(1, 'Egg'), (2, 'Sea weed'), (3, 'Pork'), (4, 'Garlic'), (5, 'None')], default=3),
        ),
    ]
