# Generated by Django 3.2 on 2023-09-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_remove_ramen_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramen',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
