# Generated by Django 3.2 on 2023-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_ramen_soup_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='BEER',
            field=models.IntegerField(choices=[(1, '1 bottle Asahi Super Dry'), (2, '1 bottle Saporro Premium'), (3, '1 bottle Echigo Koshihikari'), (4, '1 bottle Orion Premium Draft Beer'), (5, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='CHOYA',
            field=models.IntegerField(choices=[(1, '1 bottle original favor'), (2, '1 bottle hoeny favor'), (3, '1 bottle peach favor'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='SAKE',
            field=models.IntegerField(choices=[(1, '1 bottle Dassai Sake'), (2, '1 bottle Kubota Sake'), (3, '1 bottle Yamamoto Sake'), (4, '1 bottle Juyondai Sake'), (5, 'None')], default=1),
        ),
    ]
