# Generated by Django 3.2 on 2023-09-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_drink_choya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='toppings_choice',
            field=models.IntegerField(choices=[(1, 'Egg'), (2, 'Sea weed'), (3, 'Pork'), (4, 'Corn'), (5, 'None')], default=3),
        ),
    ]
