# Generated by Django 3.2 on 2023-10-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20231002_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='ramen',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=5, null=True),
        ),
    ]
