# Generated by Django 3.2 on 2023-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20231004_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drink',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='order.Drink'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='ramen',
        ),
        migrations.AddField(
            model_name='order',
            name='ramen',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='order.Ramen'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='sushi',
        ),
        migrations.AddField(
            model_name='order',
            name='sushi',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='order.Sushi'),
        ),
    ]
