# Generated by Django 3.2 on 2023-10-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_auto_20231006_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(related_name='orders', to='order.Drink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ramen',
            field=models.ManyToManyField(related_name='orders', to='order.Ramen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sushi',
            field=models.ManyToManyField(related_name='orders', to='order.Sushi'),
        ),
    ]
