# Generated by Django 3.2 on 2023-10-08 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0041_auto_20231006_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='BEER',
            new_name='beer',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='CHOYA',
            new_name='choya',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='GREEN_TEA',
            new_name='green_tea',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='SAKE',
            new_name='sake',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='WATER',
            new_name='water',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='INARI_SUSHI',
            new_name='inari_sushi',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='MAKI_SUSHI',
            new_name='maki_sushi',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='NIGIRI_SUSHI',
            new_name='nigiri_sushi',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='SOY_OIL',
            new_name='soy_oil',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='TEMAKI_SUSHI',
            new_name='temaki_sushi',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='WASABI',
            new_name='wasabi',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ramen',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sushi',
            name='customer',
        ),
        migrations.AddField(
            model_name='confirm',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
