# Generated by Django 3.2 on 2023-10-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20231008_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='water',
            field=models.IntegerField(choices=[(1, 0), (2, 0)], default=1),
        ),
    ]
