# Generated by Django 3.2 on 2023-10-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_drink_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='water',
            field=models.IntegerField(choices=[(1, '1 cup'), (2, 'None')], default=1),
        ),
    ]
