# Generated by Django 3.2 on 2023-10-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_drink_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushi',
            name='maki_sushi',
            field=models.IntegerField(choices=[(1, 'salmon, tuna, amberjack x 6'), (2, 'cucumber, carrot and egg x 6'), (3, 'sesame, cucumber, egg, crab stick x 6'), (4, 'None')], default=3),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='temaki_sushi',
            field=models.IntegerField(choices=[(1, 'Crab, cucumber x 3 '), (2, 'shrimp, cucumber  x 3 '), (3, 'Ikura, egg, salad  x 3 '), (4, 'Salmon  x 3 '), (5, 'None')], default=4),
        ),
    ]
