# Generated by Django 3.2 on 2023-10-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20231010_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm',
            name='number_of_people',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
