# Generated by Django 3.2 on 2023-10-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_alter_confirm_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm',
            name='number_of_people',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
