# Generated by Django 3.2 on 2023-10-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_alter_confirm_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='toppings_choice',
            field=models.IntegerField(choices=[(1, 'Egg'), (2, 'Sea weed'), (3, 'Pork'), (4, 'Corn'), (5, 'None')], default=1),
        ),
    ]
