# Generated by Django 3.2 on 2023-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_alter_ramen_toppings_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='side_dish',
            field=models.IntegerField(choices=[(1, 'Gyoza dumpling'), (2, 'Edamame beans'), (3, 'Yakitori skewers (chicken, beef)'), (4, 'Tempura (Chilli squid )'), (5, 'kimchi'), (6, 'fried chicken'), (7, 'None')]),
        ),
        migrations.AlterField(
            model_name='ramen',
            name='soup_choice',
            field=models.IntegerField(choices=[(1, 'pork bones soup'), (2, 'Salt soup'), (3, 'miso soup'), (4, 'soy sauce soup'), (5, 'None')]),
        ),
        migrations.AlterField(
            model_name='ramen',
            name='toppings_choice',
            field=models.IntegerField(choices=[(1, 'Egg'), (2, 'Sea weed'), (3, 'Pork'), (4, 'Corn'), (5, 'None')]),
        ),
    ]
