# Generated by Django 3.2 on 2023-10-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_auto_20231026_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='beer',
            field=models.IntegerField(choices=[(1, '1 bottle Asahi Super Dry'), (2, '1 bottle Saporro Premium'), (3, '1 bottle Echigo Koshihikari'), (4, '1 bottle Orion Premium Draft Beer'), (5, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='choya',
            field=models.IntegerField(choices=[(1, '1 bottle original favor'), (2, '1 bottle hoeny favor'), (3, '1 bottle peach favor'), (4, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='green_tea',
            field=models.IntegerField(choices=[(1, '1 cup'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='sake',
            field=models.IntegerField(choices=[(1, '1 bottle Dassai Sake'), (2, '1 bottle Kubota Sake'), (3, '1 bottle Yamamoto Sake'), (4, '1 bottle Juyondai Sake'), (5, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='water',
            field=models.IntegerField(choices=[(1, '1 cup'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='ramen',
            name='side_dish',
            field=models.IntegerField(choices=[(1, 'Gyoza dumpling'), (2, 'Edamame beans'), (3, 'Yakitori skewers (chicken, beef)'), (4, 'Tempura (Chilli squid )'), (5, 'kimchi'), (6, 'fried chicken'), (7, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='ramen',
            name='soup_choice',
            field=models.IntegerField(choices=[(1, 'pork bones soup'), (2, 'Salt soup'), (3, 'miso soup'), (4, 'soy sauce soup'), (5, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='ramen',
            name='toppings_choice',
            field=models.IntegerField(choices=[(1, 'Egg'), (2, 'Sea weed'), (3, 'Pork'), (4, 'Corn'), (5, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='inari_sushi',
            field=models.IntegerField(choices=[(1, 'Inari Sushi  x 3 '), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='maki_sushi',
            field=models.IntegerField(choices=[(1, 'salmon, tuna, amberjack x 6'), (2, 'cucumber, carrot and egg x 6'), (3, 'sesame, cucumber, egg, crab stick x 6'), (4, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='nigiri_sushi',
            field=models.IntegerField(choices=[(1, 'raw salmon x 3 '), (2, 'raw tuna  x 3 '), (3, 'shrimp  x 3 '), (4, 'sea urchin  x 3 '), (5, 'ikura  x 3 '), (6, 'amberjack  x 3 '), (7, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='soy_oil',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='temaki_sushi',
            field=models.IntegerField(choices=[(1, 'Crab, cucumber x 3 '), (2, 'shrimp, cucumber  x 3 '), (3, 'Ikura, egg, salad  x 3 '), (4, 'Salmon  x 3 '), (5, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='wasabi',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
    ]
